'use client';
import { useEffect, useMemo, useState } from 'react';
import { Search, SlidersHorizontal } from 'lucide-react';
import ProductGrid from '@/components/product-grid';
import { useStore } from '@/components/store-provider';

export default function ShopPage(){
  const { products }=useStore();
  const [q,setQ]=useState(''); const [category,setCategory]=useState('All'); const [size,setSize]=useState('All'); const [condition,setCondition]=useState('All'); const [brand,setBrand]=useState('All'); const [maxPrice,setMaxPrice]=useState(100); const [sort,setSort]=useState('featured'); const [showFilters,setShowFilters]=useState(false); const [badge,setBadge]=useState<string|null>(null);
  useEffect(()=>{const params=new URLSearchParams(window.location.search);setCategory(params.get('category')||'All');setSort(params.get('sort')||'featured');setBadge(params.get('badge'))},[]);
  const brands=Array.from(new Set(products.map(p=>p.brand))).sort(); const sizes=Array.from(new Set(products.map(p=>p.size)));
  const categories=Array.from(new Set(products.map(p=>p.category).filter(Boolean))).sort();
  const filtered=useMemo(()=>{
    let list=products.filter(p=>p.price<=maxPrice && (category==='All'||p.category===category) && (size==='All'||p.size===size) && (condition==='All'||p.condition===condition) && (brand==='All'||p.brand===brand) && (!badge || (badge==='vintage'&&p.vintageFind)) && `${p.name} ${p.brand} ${p.category}`.toLowerCase().includes(q.toLowerCase()));
    if(sort==='price-low') list.sort((a,b)=>a.price-b.price); if(sort==='price-high') list.sort((a,b)=>b.price-a.price); if(sort==='newest') list.sort((a,b)=>b.createdAt.localeCompare(a.createdAt)); if(sort==='featured') list.sort((a,b)=>Number(b.featured)-Number(a.featured)); return list;
  },[products,q,category,size,condition,brand,maxPrice,sort,badge]);
  const filters=<div className="filter-panel" style={showFilters?{display:'block',position:'static',marginBottom:18}:{}}><div className="filter-group"><h4>Category</h4><select className="control" value={category} onChange={e=>setCategory(e.target.value)}><option>All</option>{categories.map(x=><option key={x}>{x}</option>)}</select></div><div className="filter-group"><h4>Price up to</h4><input type="range" min="0" max="100000" value={maxPrice} onChange={e=>setMaxPrice(Number(e.target.value))} style={{width:'100%'}}/><label>Rs. {maxPrice}</label></div><div className="filter-group"><h4>Size</h4><select className="control" value={size} onChange={e=>setSize(e.target.value)}><option>All</option>{sizes.map(x=><option key={x}>{x}</option>)}</select></div><div className="filter-group"><h4>Condition</h4><select className="control" value={condition} onChange={e=>setCondition(e.target.value)}><option>All</option>{['Like New','Excellent','Good','Fair'].map(x=><option key={x}>{x}</option>)}</select></div><div className="filter-group"><h4>Brand</h4><select className="control" value={brand} onChange={e=>setBrand(e.target.value)}><option>All</option>{brands.map(x=><option key={x}>{x}</option>)}</select></div><button className="btn ghost" style={{width:'100%'}} onClick={()=>{setCategory('All');setSize('All');setCondition('All');setBrand('All');setMaxPrice(100);setQ('')}}>Clear filters</button></div>;
  return <div className="container"><div className="page-hero"><span className="eyebrow">The rack is open</span><h1>Shop all finds.</h1><p>Each item is photographed, measured, and condition-checked. One-of-one means exactly that—once it sells, it’s gone.</p></div><div className="shop-layout">{filters}<div><div className="shop-topbar"><div className="search-wrap"><Search size={18}/><input className="control" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search pieces, brands, categories..."/></div><button className="btn ghost mobile-filter" onClick={()=>setShowFilters(v=>!v)}><SlidersHorizontal size={17}/> Filters</button><select className="control" style={{maxWidth:200}} value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Featured</option><option value="newest">Newest</option><option value="price-low">Price: low to high</option><option value="price-high">Price: high to low</option></select></div>{showFilters&&filters}<div className="result-count">{filtered.length} pieces</div>{filtered.length?<ProductGrid products={filtered}/>:<div className="empty-state"><h3>No pieces match that mix.</h3><p>Try clearing a filter or searching a broader term.</p></div>}</div></div></div>
}
